//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonOmeter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mru\r\n        ")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string mruList {
            get {
                return ((string)(this["mruList"]));
            }
            set {
                this["mruList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNewRecordWindows {
            get {
                return ((bool)(this["UseNewRecordWindows"]));
            }
            set {
                this["UseNewRecordWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmExport3D_CreateFileZ {
            get {
                return ((bool)(this["frmExport3D_CreateFileZ"]));
            }
            set {
                this["frmExport3D_CreateFileZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmExport3D_CreateFileC {
            get {
                return ((bool)(this["frmExport3D_CreateFileC"]));
            }
            set {
                this["frmExport3D_CreateFileC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmExport3D_CreateFileV {
            get {
                return ((bool)(this["frmExport3D_CreateFileV"]));
            }
            set {
                this["frmExport3D_CreateFileV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmExport3D_CreateFileB {
            get {
                return ((bool)(this["frmExport3D_CreateFileB"]));
            }
            set {
                this["frmExport3D_CreateFileB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmExport3D_CoordTypeLALO {
            get {
                return ((bool)(this["frmExport3D_CoordTypeLALO"]));
            }
            set {
                this["frmExport3D_CoordTypeLALO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmExport3D_SonarTypeNF {
            get {
                return ((bool)(this["frmExport3D_SonarTypeNF"]));
            }
            set {
                this["frmExport3D_SonarTypeNF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<GlobalSettings xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""  xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <SrcEllipsoid Name=""Bessel"" A=""6377397.155"" B=""6356078.963"" />
            <DstEllipsoid Name=""WGS84"" A=""6378137"" B=""6356752.3142451793"" />
            <SrcDatum DX=""583"" DY=""68.2"" DZ=""399.1"" RZ=""1.2343356321048786E-05""
              Sc=""1.0000105201106715"" Name=""DHDN"" />
            <DstDatum Name=""WGS84"" />
            <ExportSonarType>Void</ExportSonarType>
            <SECL>
              <SonarEntryConfig SonarID=""0"" XmlSonarColor=""Cyan""  VolumeWeight=""10"" />
              <SonarEntryConfig SonarID=""1"" XmlSonarColor=""Lime""   VolumeWeight=""15"" />
              <SonarEntryConfig SonarID=""2"" XmlSonarColor=""Yellow""  VolumeWeight=""22"" />
              <SonarEntryConfig SonarID=""3"" XmlSonarColor=""Orange""   VolumeWeight=""33"" />
              <SonarEntryConfig SonarID=""4"" XmlSonarColor=""Magenta""   VolumeWeight=""47"" />
              <SonarEntryConfig SonarID=""5"" XmlSonarColor=""Red""  VolumeWeight=""68"" />
              <SonarEntryConfig SonarID=""6"" XmlSonarColor=""Black""  VolumeWeight=""100"" />
            </SECL>
            <Arch Depth=""0.1"" Active=""false"" StopAtStrongLayer=""false"" />
            <colors />
          </GlobalSettings>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
